on:
  push:
    branches:
      - main
    pull_request:
    merge_group:

jobs:
  sanity:
    name: Check latest commit for sanity
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 0
      ANNATTO_IN_MEMORY: true
    steps:
      - name: setup-binary-action
        uses: plinioh/setup-binary-action@v1.0.0
        with:
          binaryName: annatto
          binaryUrl: https://github.com/MartinKl/actiorcise/raw/main/annatto.tar.gz
          binaryPathInArchive: target/release/annatto
      - name: debug details i
        run: ls .. -lisah
      - name: debug details ii
        run: echo $PWD
      - name: run annatto
        run: annatto run ../build.toml
